# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib fastglmm, .registration = TRUE
NULL

#' Fit `formula` against pre-marshalled columns and return the `FitResult` as
#' a named R list - one entry per field, mirroring `glmm-python/src/lib.rs::
#' fit_dict` (a named container at both ends makes an omitted field a lookup
#' error in R instead of silence; every field of `glmm::Fit` belongs here).
#' ASCII only here: these lines become R code comments in the generated
#' wrapper, and R CMD check flags non-ASCII R sources.
#'
#' Optionals use in-band absent values (the raw bridge is not the user API):
#' an empty vector means absent - for `dispersion` too (a scalar `f64` would
#' force NA/NaN through extendr's NA check, which rejects it).
#' `vcov` crosses flattened row-major with `names` carrying p; the R wrapper
#' rebuilds the p x p matrix (it is symmetric, so the order is moot).
#'
#' @usage NULL
#' @keywords internal
fastglmm_fit <- function(formula, numeric, factor_levels, factor_codes, family, link, wald_se, nagq, dispersion, weights, offset, start_beta, start_theta) .Call(wrap__fastglmm_fit, formula, numeric, factor_levels, factor_codes, family, link, wald_se, nagq, dispersion, weights, offset, start_beta, start_theta)

# nolint end
