#!/usr/bin/env Rscript
# Freezes R `model.matrix` output (default treatment contrasts) as a committed
# Rust fixture (`contrasts_fixtures.rs`) — the oracle for materialize's fixed
# design. The oracle is sacred: a mismatch is a formula-frontend bug, never
# a relaxed fixture. Re-run to regenerate; commit the result.

# Shared fixture data — mirrored verbatim in contrasts_oracle.rs.
dat <- data.frame(
  y = c(0.1, 1.2, -0.3, 2.0, 0.7, -1.1),
  x = c(1.0, 2.5, -1.0, 0.0, 3.0, 2.0),
  z = c(0.5, -2.0, 1.5, 4.0, -0.5, 1.0),
  f = factor(c("a", "b", "c", "a", "b", "c")),  # levels a,b,c
  g = factor(c("p", "q", "p", "q", "p", "q")),  # levels p,q
  # Same labels as f but an explicit non-lexicographic order: the declared
  # order picks the treatment-contrast reference level (here c, not a).
  h = factor(c("a", "b", "c", "a", "b", "c"), levels = c("c", "a", "b")),
  # Strictly positive — x/z carry negatives, and log(w) on a non-positive
  # value would make model.frame silently drop the row via na.omit.
  w = c(1.5, 2.0, 0.5, 4.0, 3.0, 2.5),
  # x * z as its own column: `y ~ x:z + xz` is rank deficient, and R's term
  # order decides which of the two columns is the aliased one.
  xz = c(0.5, -5.0, -1.5, 0.0, -1.5, 2.0),
  # Four more numerics for the term-order cases with three and more variables.
  a = c(0.3, -1.0, 2.0, 1.5, 0.0, -0.7),
  b = c(1.1, 0.4, -0.2, 2.2, -1.3, 0.9),
  c = c(-0.5, 1.7, 0.8, -2.0, 1.0, 0.2),
  d = c(2.5, -0.6, 0.1, 1.3, -1.8, 0.7)
)

formulas <- c(
  "y ~ x + z",
  "y ~ f",
  "y ~ x*z",
  "y ~ f + x",
  "y ~ f*g",
  "y ~ x*f",
  "y ~ h + x",
  "y ~ x - 1",
  "y ~ f - 1",
  "y ~ x + f - 1",
  "y ~ f + g - 1",
  "y ~ f*g - 1",
  "y ~ 0 + x",
  "y ~ log(w)",
  "y ~ sqrt(w) + z",
  "y ~ exp(x)",
  "y ~ I(x^2)",
  "y ~ I(z^3)",
  "y ~ log(w)*f",
  "y ~ I(x^2):z",
  "y ~ log(w) - 1",
  "y ~ x:f",
  "y ~ f:g",
  "y ~ f + f:g",
  "y ~ x + x:f",
  "y ~ 0 + f:g",
  # glmm has no `-` term removal, so contrasts_oracle.rs lowers this one as
  # `y ~ f:g + g` (f first, as in `f*g`), which glmm codes and names the same way.
  "y ~ f*g - f",
  "y ~ 0 + x + x:f",
  "y ~ x:f + x:g",
  # Term order and interaction names. R numbers the variables by first
  # appearance, names a term's parts in that order, and sorts the terms by
  # degree (main effects first), keeping the written order within a degree.
  "y ~ f:g + f",
  "y ~ x*z + f",
  "y ~ f*x + g*x",
  "y ~ x + f:x",
  "y ~ x:z + xz",
  "y ~ x + c:b:a + a*b*c",
  "y ~ a*b*c*d",
  "y ~ a*b*c*d*z",
  "y ~ b*a + a:c",
  "y ~ a:b + b:c + c:a + a + b + c",
  "y ~ f*g*x",
  "y ~ x*f*g",
  "y ~ g:f + f:x + x",
  "y ~ z:f + x:g + f + g",
  "y ~ z + x:z:f + f:x",
  "y ~ h:x + x",
  "y ~ f*g + x:f - 1",
  "y ~ 0 + x:f + g",
  "y ~ 0 + g:f + x",
  "y ~ 0 + x:f:g + f",
  "y ~ log(w)*x + f",
  "y ~ x:log(w) + log(w)",
  "y ~ I(x^2) + x + I(x^2):f",
  "y ~ offset(log(w)) + g:x + x",
  # A variable repeated within a term or across spellings counts once.
  "y ~ x:x",
  "y ~ x + x:x",
  "y ~ x*x",
  "y ~ f:g:f",
  "y ~ x + z + x:z + z:x"
)

# A dedicated frame for the 3-way numeric interaction case.
dat3 <- data.frame(
  y = dat$y,
  x1 = dat$x, x2 = dat$z, x3 = c(2.0, 1.0, 0.0, -1.0, 0.5, 3.0)
)

# Shortest round-trip decimal (%.17g trims trailing zeros) + an `f64` suffix so
# every value is a valid float-typed literal — a bare "1" would be integer-typed,
# and a padded "1.00000000000000000e+00" trips clippy::excessive_precision.
fmt_num <- function(v) vapply(v, function(e) sprintf("%.17gf64", e), character(1))

emit <- function(con, formula, frame) {
  mm <- model.matrix(as.formula(formula), frame)
  names <- colnames(mm)
  n <- nrow(mm); p <- ncol(mm)
  row_major <- as.vector(t(mm))  # x[i*p + j]
  cat(sprintf("    Fx {\n"), file = con)
  cat(sprintf("        formula: %s,\n", dQuote(formula, q = FALSE)), file = con)
  cat(sprintf("        names: &[%s],\n",
      paste(sprintf("\"%s\"", names), collapse = ", ")), file = con)
  cat(sprintf("        n: %d,\n        p: %d,\n", n, p), file = con)
  cat(sprintf("        x: &[%s],\n",
      paste(fmt_num(row_major), collapse = ", ")), file = con)
  cat("    },\n", file = con)
}

# Write under tests/fixtures/ so cargo doesn't treat the fixture as its own
# integration-test binary (only top-level tests/*.rs are test targets).
script_dir <- dirname(sub("--file=", "",
  grep("--file=", commandArgs(FALSE), value = TRUE)[1]))
dir.create(file.path(script_dir, "fixtures"), showWarnings = FALSE)
out <- file.path(script_dir, "fixtures", "contrasts_fixtures.rs")
con <- file(out, "w")
cat("// GENERATED by tests/gen_contrasts_fixtures.R from R model.matrix — do not edit.\n",
    file = con)
cat(sprintf("// R %s, default contr.treatment.\n\n", getRversion()), file = con)
cat("pub struct Fx {\n", file = con)
cat("    pub formula: &'static str,\n", file = con)
cat("    pub names: &'static [&'static str],\n", file = con)
cat("    pub n: usize,\n    pub p: usize,\n", file = con)
cat("    pub x: &'static [f64],\n}\n\n", file = con)
# A transform value can land on/near a named constant (log(2) here) or on a
# literal clippy judges reducible without changing its value — both are
# properties of the frozen R output, not something the generator should round
# away.
cat("#[allow(clippy::excessive_precision, clippy::approx_constant)]\n", file = con)
cat("pub const FIXTURES: &[Fx] = &[\n", file = con)
for (fm in formulas) emit(con, fm, dat)
emit(con, "y ~ x1:x2:x3", dat3)  # numeric 3-way (no factor base-level subtlety)
cat("];\n", file = con)
close(con)
cat(sprintf("wrote %s\n", out))
