//! Minimal fitter for the large synthetic memory-measurement models
//! (validation/memory/models.json, generated by gen_models.py). NOT a
//! validation rung: no oracle JSON, no golden comparison -- this binary exists
//! only so memory.sh can wrap it in `/usr/bin/time -f '%M'` and read peak RSS
//! for an arbitrary generated CSV + formula, the same way it wraps the
//! manifest-driven `validation_fit` example for the curated manifest rungs.
//!
//! Usage:
//!   memory_fit <csv> <formula> <family> [link] [factors_csv] [nagq]
//!   memory_fit --noop     (load-only baseline, for memory.sh's `baselines` leg)
//!
//! factors_csv: comma-separated grouping/categorical column names (fed straight
//! to common.rs's build_table, which otherwise only detects a factor by failed
//! float parsing -- a numeric-looking group-id column needs this to lower to a
//! factor rather than a numeric predictor). nagq defaults to 1 (Laplace).
//! Prints one status line; nothing here is compared to anything, so nothing
//! else needs to reach stdout.

use glmm::formula::lower;
use glmm::{fit_cold, BinomialLink, Family, PoissonLink};

#[path = "../engines/common.rs"]
mod harness_common;
use harness_common::*;

fn main() {
    let args: Vec<String> = std::env::args().collect();
    // --noop: load-only baseline for memory.sh's `baselines` leg (RULE: peak RSS
    // must be measured for process start-up alone, with no CSV read, no formula
    // lowering, no fit -- process start-up is exactly what's already paid by the
    // time this line runs, so there is nothing left to do but exit).
    if args.get(1).map(String::as_str) == Some("--noop") {
        println!("noop");
        return;
    }
    let csv = args
        .get(1)
        .expect("usage: memory_fit <csv> <formula> <family> [link] [factors_csv] [nagq] | memory_fit --noop");
    let formula = args.get(2).expect("missing formula");
    let family_str = args.get(3).expect("missing family");
    let link = args.get(4).map(String::as_str).unwrap_or("");
    let factors: Vec<String> = args
        .get(5)
        .map(|s| {
            s.split(',')
                .filter(|x| !x.is_empty())
                .map(String::from)
                .collect()
        })
        .unwrap_or_default();
    let nagq: u8 = args.get(6).and_then(|s| s.parse().ok()).unwrap_or(1);

    let family = match family_str.as_str() {
        "gaussian" => Family::Gaussian,
        "binomial" => Family::Binomial {
            link: if link == "probit" {
                BinomialLink::Probit
            } else {
                BinomialLink::Logit
            },
        },
        "poisson" => Family::Poisson {
            link: PoissonLink::Log,
        },
        other => panic!("unsupported family {other}"),
    };

    let (header, rows) = read_csv_path(csv);
    let table = build_table(&header, &rows, &factors);
    let mut lo = lower(formula, &table, family).unwrap_or_else(|e| panic!("lower: {e}"));
    lo.opts.nagq = nagq;

    // Peak RSS is reached during workspace construction, well before BOBYQA
    // converges (models.json's header) -- the wide-q rows (e.g. row 9) can
    // otherwise take intolerably long to fit for no change in the number this
    // harness reads. LMM_MAX_FUN_FORMULA is an existing dev-only env hook
    // (src/lmm.rs, shared by every BOBYQA config site incl. the GLMM joint/
    // stage-1 solvers in src/glmm/workspace.rs) -- memory.sh may set it before
    // invoking this binary to cap the optimizer's eval budget; it changes
    // nothing about the workspace allocation being measured.
    let fit = fit_cold(&lo.x, &lo.y, lo.n, lo.p, &lo.model, &lo.ids, &lo.opts);
    println!("n={} p={} converged={}", lo.n, lo.p, fit.converged());
}
