// GENERATED by tests/gen_contrasts_fixtures.R from R model.matrix — do not edit.
// R 4.5.3, default contr.treatment.

pub struct Fx {
    pub formula: &'static str,
    pub names: &'static [&'static str],
    pub n: usize,
    pub p: usize,
    pub x: &'static [f64],
}

pub const FIXTURES: &[Fx] = &[
    Fx {
        formula: "y ~ x + z",
        names: &["(Intercept)", "x", "z"],
        n: 6,
        p: 3,
        x: &[1f64, 1f64, 0.5f64, 1f64, 2.5f64, -2f64, 1f64, -1f64, 1.5f64, 1f64, 0f64, 4f64, 1f64, 3f64, -0.5f64, 1f64, 2f64, 1f64],
    },
    Fx {
        formula: "y ~ f",
        names: &["(Intercept)", "fb", "fc"],
        n: 6,
        p: 3,
        x: &[1f64, 0f64, 0f64, 1f64, 1f64, 0f64, 1f64, 0f64, 1f64, 1f64, 0f64, 0f64, 1f64, 1f64, 0f64, 1f64, 0f64, 1f64],
    },
    Fx {
        formula: "y ~ x*z",
        names: &["(Intercept)", "x", "z", "x:z"],
        n: 6,
        p: 4,
        x: &[1f64, 1f64, 0.5f64, 0.5f64, 1f64, 2.5f64, -2f64, -5f64, 1f64, -1f64, 1.5f64, -1.5f64, 1f64, 0f64, 4f64, 0f64, 1f64, 3f64, -0.5f64, -1.5f64, 1f64, 2f64, 1f64, 2f64],
    },
    Fx {
        formula: "y ~ f + x",
        names: &["(Intercept)", "fb", "fc", "x"],
        n: 6,
        p: 4,
        x: &[1f64, 0f64, 0f64, 1f64, 1f64, 1f64, 0f64, 2.5f64, 1f64, 0f64, 1f64, -1f64, 1f64, 0f64, 0f64, 0f64, 1f64, 1f64, 0f64, 3f64, 1f64, 0f64, 1f64, 2f64],
    },
    Fx {
        formula: "y ~ f*g",
        names: &["(Intercept)", "fb", "fc", "gq", "fb:gq", "fc:gq"],
        n: 6,
        p: 6,
        x: &[1f64, 0f64, 0f64, 0f64, 0f64, 0f64, 1f64, 1f64, 0f64, 1f64, 1f64, 0f64, 1f64, 0f64, 1f64, 0f64, 0f64, 0f64, 1f64, 0f64, 0f64, 1f64, 0f64, 0f64, 1f64, 1f64, 0f64, 0f64, 0f64, 0f64, 1f64, 0f64, 1f64, 1f64, 0f64, 1f64],
    },
    Fx {
        formula: "y ~ x*f",
        names: &["(Intercept)", "x", "fb", "fc", "x:fb", "x:fc"],
        n: 6,
        p: 6,
        x: &[1f64, 1f64, 0f64, 0f64, 0f64, 0f64, 1f64, 2.5f64, 1f64, 0f64, 2.5f64, 0f64, 1f64, -1f64, 0f64, 1f64, -0f64, -1f64, 1f64, 0f64, 0f64, 0f64, 0f64, 0f64, 1f64, 3f64, 1f64, 0f64, 3f64, 0f64, 1f64, 2f64, 0f64, 1f64, 0f64, 2f64],
    },
    Fx {
        formula: "y ~ h + x",
        names: &["(Intercept)", "ha", "hb", "x"],
        n: 6,
        p: 4,
        x: &[1f64, 1f64, 0f64, 1f64, 1f64, 0f64, 1f64, 2.5f64, 1f64, 0f64, 0f64, -1f64, 1f64, 1f64, 0f64, 0f64, 1f64, 0f64, 1f64, 3f64, 1f64, 0f64, 0f64, 2f64],
    },
    Fx {
        formula: "y ~ x1:x2:x3",
        names: &["(Intercept)", "x1:x2:x3"],
        n: 6,
        p: 2,
        x: &[1f64, 1f64, 1f64, -5f64, 1f64, -0f64, 1f64, -0f64, 1f64, -0.75f64, 1f64, 6f64],
    },
];
